name: Build and Release Python Package

on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
  actions: write
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Poetry
      run: pip install poetry
    - name: Build Wheel
      run: poetry build --format wheel
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.whl
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

